---
all:
  children:
   centos:
    hosts:
     centos1:
    vars:
     ansible_user: root
   ubuntu:
    hosts:
     ubuntu1:
    vars:
     ansible_become: true
     ansible_become_pass: vagrant
...	
