---
all:
  children:
   control:
    hosts:
     ubuntuacs:
    vars:
     ansible_connection: local
   centos:
    hosts:
     centos1: 
    vars:
     ansible_user: root
     ansible_port: 2222
   ubuntu:
    hosts:
     ubuntu1:
    vars:
     ansible_become: true
     ansible_become_pass: vagrant
...	
